title: "Praveen Prakash"
description: "Ramblings and Rants."
url: "https://praveenprakash.com"   # your GitHub Pages root
baseurl: ""                               # keep empty for user site (not /blog)

# Theme
theme: minima

# Sass / CSS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed

# Markdown / Kramdown
markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1